/**
 * Contenu MOCKÉ du calendrier de l'avent 2026 — Ligue 1 McDonald's.
 * 24 cases, 4 mécaniques réparties (6 de chaque) : lot, exclusif, quiz, promo.
 * Lots, codes promo et contenus sont fictifs : à remplacer par la validation
 * marketing / partenariats / juridique (règlement du jeu) avant mise en ligne.
 * club: id de CLUBS_L1 (js/data.js) ou null = case "Ligue" (logo compétition).
 */

const ADVENT_YEAR = 2026;

const ADVENT_TYPES = {
  lot: { label: "À gagner", icon: "🎁" },
  exclusif: { label: "Exclusif", icon: "▶" },
  quiz: { label: "Quiz", icon: "?" },
  promo: { label: "Code promo", icon: "%" },
};

// Points gagnés : bonne réponse au quiz, participation à un concours.
const ADVENT_POINTS = { quizCorrect: 10, lotEntry: 5, open: 1 };

const ADVENT_DAYS = [
  { day: 1, type: "lot", club: null, big: true,
    title: "Le ballon officiel de la saison",
    text: "On lance l'avent avec le ballon officiel Ligue 1 McDonald's 2026-2027. Participe aujourd'hui pour tenter ta chance.",
    winners: 10 },
  { day: 2, type: "quiz", club: "losc",
    title: "Quiz : le surnom",
    question: "Quel est le surnom des joueurs du LOSC ?",
    options: ["Les Dogues", "Les Merlus", "Les Aiglons", "Les Canaris"], answer: 0,
    explain: "Les Dogues : un surnom qui colle au club lillois depuis des décennies." },
  { day: 3, type: "promo", club: null,
    partner: "McDonald's",
    title: "Ton menu de match",
    text: "Une offre spéciale soirée de match dans l'appli McDonald's.",
    code: "L1NOEL03", validity: "Valable jusqu'au 10 décembre" },
  { day: 4, type: "exclusif", club: "rcl",
    title: "Bollaert sous la neige",
    text: "Les coulisses d'un soir d'hiver à Bollaert-Delelis, des vestiaires jusqu'au virage.",
    media: "video", duration: "4 min" },
  { day: 5, type: "lot", club: "om",
    title: "Un maillot dédicacé",
    text: "Le maillot domicile de l'OM, signé par l'effectif.",
    winners: 1 },
  { day: 6, type: "quiz", club: "om",
    title: "Quiz : la nuit de Munich",
    question: "En quelle année l'OM a-t-il remporté la Ligue des champions ?",
    options: ["1991", "1993", "1996", "2004"], answer: 1,
    explain: "Le 26 mai 1993, face à l'AC Milan. Premier club français à soulever la C1." },
  { day: 7, type: "exclusif", club: null,
    title: "Fond d'écran de Noël",
    text: "Le fond d'écran officiel de l'avent, en version mobile et desktop.",
    media: "wallpaper" },
  { day: 8, type: "promo", club: null,
    partner: "Boutique officielle",
    title: "-20 % sur les maillots",
    text: "Sur une sélection de maillots des 18 clubs.",
    code: "AVENT20", validity: "Valable jusqu'au 15 décembre" },
  { day: 9, type: "lot", club: "srfc", big: true,
    title: "2 places au Roazhon Park",
    text: "Deux places en tribune pour un match du Stade Rennais à domicile en 2027.",
    winners: 2 },
  { day: 10, type: "quiz", club: "hac",
    title: "Quiz : le doyen",
    question: "Quel club est considéré comme le doyen du football français ?",
    options: ["Le Havre AC", "AJ Auxerre", "FC Lorient", "RC Strasbourg"], answer: 0,
    explain: "Le Havre AC, fondé en 1872, est le plus ancien club de football de France." },
  { day: 11, type: "exclusif", club: "psg",
    title: "Les plus beaux buts de 2026",
    text: "Le best-of des plus belles frappes de l'année civile, toutes compétitions L1 confondues.",
    media: "video", duration: "6 min" },
  { day: 12, type: "promo", club: null, big: true,
    partner: "Ligue 1+",
    title: "Un mois offert",
    text: "Pour regarder la reprise de janvier sans rien rater.",
    code: "L1PLUSNOEL", validity: "Nouveaux abonnés, jusqu'au 31 décembre" },
  { day: 13, type: "lot", club: "ogcn",
    title: "Visite de l'Allianz Riviera",
    text: "Une visite des coulisses du stade pour 4 personnes, vestiaires compris.",
    winners: 1 },
  { day: 14, type: "quiz", club: "rcl",
    title: "Quiz : le stade",
    question: "Comment s'appelle le stade du RC Lens ?",
    options: ["Stade Pierre-Mauroy", "Stade Bollaert-Delelis", "Stade de la Meinau", "Stade Geoffroy-Guichard"], answer: 1,
    explain: "Bollaert-Delelis, l'un des stades les plus bouillants de France." },
  { day: 15, type: "exclusif", club: "ol",
    title: "Dans le vestiaire",
    text: "24 heures avec un staff de L1 avant un match de décembre.",
    media: "video", duration: "8 min" },
  { day: 16, type: "promo", club: null,
    partner: "McDonald's",
    title: "Le dessert offert",
    text: "Un dessert offert pour toute commande dans l'appli, les soirs de match.",
    code: "L1DESSERT", validity: "Valable jusqu'au 23 décembre" },
  { day: 17, type: "lot", club: "asm",
    title: "Écharpes collector",
    text: "L'écharpe collector de Noël de l'AS Monaco.",
    winners: 20 },
  { day: 18, type: "quiz", club: "ogcn",
    title: "Quiz : le surnom",
    question: "Quel est le surnom des joueurs de l'OGC Nice ?",
    options: ["Les Sang et Or", "Les Aiglons", "Les Dogues", "Les Merlus"], answer: 1,
    explain: "Les Aiglons, en référence à l'aigle des armoiries de la ville de Nice." },
  { day: 19, type: "exclusif", club: "rcs",
    title: "Fond d'écran : ton club",
    text: "Le fond d'écran de Noël aux couleurs de chacun des 18 clubs.",
    media: "wallpaper" },
  { day: 20, type: "promo", club: null,
    partner: "Boutique officielle",
    title: "Livraison offerte avant Noël",
    text: "Commande avant le 22 décembre, livrée sous le sapin.",
    code: "SAPIN26", validity: "Valable jusqu'au 22 décembre" },
  { day: 21, type: "quiz", club: null,
    title: "Quiz : le format",
    question: "Combien de clubs composent la Ligue 1 McDonald's ?",
    options: ["16", "18", "20", "22"], answer: 1,
    explain: "18 clubs depuis la saison 2023-2024." },
  { day: 22, type: "exclusif", club: "sb29",
    title: "Le Noël des supporters",
    text: "Tifos, chants et marchés de Noël : le mois de décembre vu des tribunes.",
    media: "video", duration: "5 min" },
  { day: 23, type: "promo", club: null,
    partner: "McDonald's",
    title: "Menu du réveillon",
    text: "Une dernière offre avant Noël dans l'appli McDonald's.",
    code: "L1VEILLE", validity: "Valable les 23 et 24 décembre" },
  { day: 24, type: "lot", club: null, big: true,
    title: "Le gros lot de Noël",
    text: "Un week-end pour deux au match de ton choix lors de la reprise de janvier : transport, hôtel et places en loges.",
    winners: 1 },
];

// Ordre d'affichage mélangé, comme sur un vrai calendrier de l'avent.
const ADVENT_LAYOUT = [1, 14, 7, 20, 3, 17, 10, 24, 5, 22, 12, 8, 19, 2, 15, 11, 23, 6, 18, 9, 4, 21, 13, 16];
